/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#526965",
        "inverse-on-surface": "#f5f0e7",
        "tertiary-fixed-dim": "#afd0a1",
        "surface-container-low": "#f8f3ea",
        "on-secondary-fixed": "#091f1c",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#b4c8e4",
        "on-tertiary-container": "#7e9d72",
        "on-tertiary": "#ffffff",
        "secondary": "#4d635f",
        "on-primary-container": "#8296b0",
        "inverse-primary": "#b4c8e4",
        "on-error-container": "#93000a",
        "surface-tint": "#4c6078",
        "tertiary-fixed": "#caecbc",
        "outline-variant": "#c4c6cd",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#b3cbc7",
        "surface": "#fef9f0",
        "on-background": "#1d1c16",
        "background": "#fef9f0",
        "surface-dim": "#ded9d1",
        "tertiary": "#041d02",
        "secondary-container": "#cfe8e3",
        "error-container": "#ffdad6",
        "surface-container": "#f2ede4",
        "surface-container-high": "#ece8df",
        "primary-fixed": "#d1e4ff",
        "secondary-fixed": "#cfe8e3",
        "tertiary-container": "#183312",
        "on-error": "#ffffff",
        "outline": "#74777d",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#324e2a",
        "on-secondary": "#ffffff",
        "inverse-surface": "#32302b",
        "surface-variant": "#e7e2d9",
        "on-primary-fixed": "#061d32",
        "on-surface": "#1d1c16",
        "surface-container-highest": "#e7e2d9",
        "primary": "#03192e",
        "on-secondary-fixed-variant": "#354b48",
        "on-tertiary-fixed": "#062104",
        "on-primary-fixed-variant": "#35485f",
        "primary-container": "#1a2e44",
        "surface-bright": "#fef9f0",
        "on-surface-variant": "#43474d",
        
        "ds-dark-surface": "#060e14",
        "ds-dark-primary": "#f5f0e7",
        "ds-dark-on-surface": "#d1d5db"
      },
      fontFamily: {
        "headline": ["Noto Serif"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      },
    },
  },
  plugins: [],
}
